service: saas-boilerplate-email

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    restApiId:
      Fn::ImportValue: SaasBoilerplateApiGateway-restApiId
    restApiRootResourceId:
      Fn::ImportValue: SaasBoilerplateApiGateway-rootResourceId
  environment:
    SES_REGION: ${self:provider.region}
    SES_SENDER_EMAIL: ${param:sesSenderEmail}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendTemplatedEmail
        - ses:VerifyEmailIdentity
        - ses:VerifyDomainIdentity
        - ses:GetIdentityVerificationAttributes
      Resource: "*"

functions:
  sendEmail:
    handler: src/handlers/email.httpHandler
    events:
      - http:
          path: send-email
          method: post
          cors: true

  handleVerificationEmail:
    handler: src/handlers/email.eventHandler
    events:
      - eventBridge:
          pattern:
            source:
              - com.saas-boilerplate.user
            detail-type:
              - VerificationEmailRequest
              - ResetPasswordEmailRequest
              - InviteMemberEmailRequest

resources:
  Resources:
    EmailIdentity:
      Type: AWS::SES::EmailIdentity
      Properties:
        EmailIdentity: ${env:SES_SENDER_EMAIL}
    SaasBoilerplateForgotPasswordTemplate:
      Type: AWS::SES::Template
      Properties:
        Template:
          TemplateName: SaasBoilerplateForgotPasswordTemplate
          SubjectPart: "Password Reset Request"
          HtmlPart: |
            <html>
              <head></head>
              <body>
                <h1>Password Reset Request</h1>
                <p>Click the link below to reset your password:</p>
                <a href="{{resetLink}}">Reset Password</a>
              </body>
            </html>
          TextPart: |
            Click the link below to reset your password:
            {{resetLink}}
    SaasBoilerplateVerifyEmailTemplate:
      Type: AWS::SES::Template
      Properties:
        Template:
          TemplateName: SaasBoilerplateVerifyEmailTemplate
          SubjectPart: "Verify Your Email"
          HtmlPart: |
            <html>
              <head></head>
              <body>
                <h1>Verify Your Email</h1>
                <p>Click the link below to verify your email:</p>
                <a href="{{verifyLink}}">Verify Email</a>
              </body>
            </html>
          TextPart: |
            Click the link below to verify your email:
            {{verifyLink}}
    SaasBoilerplateInviteMemberTemplate:
      Type: AWS::SES::Template
      Properties:
        Template:
          TemplateName: SaasBoilerplateInviteMemberTemplate
          SubjectPart: "Invite to Organization"
          HtmlPart: |
            <html>
              <head></head>
              <body>
                <h1>Invite to Organization: {{organizationName}}</h1>
                <p>Click the link below to join the organization:</p>
                <a href="{{inviteLink}}">Join Organization</a>
              </body>
            </html>
          TextPart: |
            Click the link below to join the organization:
            {{inviteLink}}
